CREATE TABLE IF NOT EXISTS `User`
(
  `id` INT NOT NULL AUTO_INCREMENT ,
  `name` VARCHAR(30) NOT NULL ,
  `age` INT NOT NULL ,
  PRIMARY KEY (`id`)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO `User` VALUES (NULL , 'kyle1' , 21);